"""Add test auto publish schedule

Revision ID: 7ba86006ea73
Revises: c8f78218c129
Create Date: 2026-07-14 14:17:38.147598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba86006ea73'
down_revision: Union[str, Sequence[str], None] = 'c8f78218c129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tests', sa.Column('unpublish_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tests_publish_at'), 'tests', ['publish_at'], unique=False)
    op.create_index(op.f('ix_tests_unpublish_at'), 'tests', ['unpublish_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_unpublish_at'), table_name='tests')
    op.drop_index(op.f('ix_tests_publish_at'), table_name='tests')
    op.drop_column('tests', 'unpublish_at')
    op.drop_column('tests', 'publish_at')
    # ### end Alembic commands ###
