"""Add scheduling and publishing

Revision ID: de79c72c2390
Revises: e0c04d262e3d
Create Date: 2026-07-13 15:33:45.679758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de79c72c2390'
down_revision: Union[str, Sequence[str], None] = 'e0c04d262e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_submissions_assignment_id'), 'assignment_submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_user_id'), 'assignment_submissions', ['user_id'], unique=False)
    op.add_column('assignments', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assignments', sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_assignments_ends_at'), 'assignments', ['ends_at'], unique=False)
    op.create_index(op.f('ix_assignments_starts_at'), 'assignments', ['starts_at'], unique=False)
    op.add_column('grades', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_grades_is_published'), 'grades', ['is_published'], unique=False)
    op.add_column('tests', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tests', sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tests', sa.Column('results_published', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tests_ends_at'), 'tests', ['ends_at'], unique=False)
    op.create_index(op.f('ix_tests_results_published'), 'tests', ['results_published'], unique=False)
    op.create_index(op.f('ix_tests_starts_at'), 'tests', ['starts_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_starts_at'), table_name='tests')
    op.drop_index(op.f('ix_tests_results_published'), table_name='tests')
    op.drop_index(op.f('ix_tests_ends_at'), table_name='tests')
    op.drop_column('tests', 'results_published')
    op.drop_column('tests', 'ends_at')
    op.drop_column('tests', 'starts_at')
    op.drop_index(op.f('ix_grades_is_published'), table_name='grades')
    op.drop_column('grades', 'is_published')
    op.drop_index(op.f('ix_assignments_starts_at'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_ends_at'), table_name='assignments')
    op.drop_column('assignments', 'ends_at')
    op.drop_column('assignments', 'starts_at')
    op.drop_index(op.f('ix_assignment_submissions_user_id'), table_name='assignment_submissions')
    op.drop_index(op.f('ix_assignment_submissions_assignment_id'), table_name='assignment_submissions')
    op.drop_table('assignment_submissions')
    # ### end Alembic commands ###
